# Header
menu:
  Home: /
  Internal-Projects: /internal
  Tags: /tags
  About: /about
menu_links:
  Github: https://github.com/The-Brotherhood-of-SCU

# Content
excerpt_link: 阅读全文
# 自动折叠
auto_fold: true

default_image: /images/banner/banner.avif

# MIIT ICP/IP/DOMAIN
beian: 
  enable: false
  number: 
  url: https://beian.miit.gov.cn/

# Miscellaneous
favicon: https://avatars.githubusercontent.com/u/154577967?s=48&v=4
webclip: 
brand:   /images/brand.png

# Jumbotron video & Hero image & Swiper
## Jumbotron video
video: 
  overlay: false
  path: /images/movie/
## Hero image
hero: 
  image: /images/banner/banner.avif
## Swiper
## https://github.com/nolimits4web/swiper
swiper: 
  enable: false

# Toc
## https://github.com/tscanlin/tocbot
toc: true

# Slogan
slogan: 
  primary: The Brotherhood of SCU
  secondary: Find Anything Here
  archives: 
  pages: 
  posts: 

# Katex
katex:
  enable: true


# Library
libs:
  feather: https://cdn.jsdelivr.net/npm/feather-icons/dist/feather.min.js
  lazysizes: https://cdnjs.cloudflare.com/ajax/libs/lazysizes/5.3.2/lazysizes.min.js
  tocbot: https://cdnjs.cloudflare.com/ajax/libs/tocbot/4.32.2/tocbot.min.js
  swiper: 
    css: https://cdnjs.cloudflare.com/ajax/libs/Swiper/11.0.5/swiper-bundle.min.css
    js:  https://cdnjs.cloudflare.com/ajax/libs/Swiper/11.0.5/swiper-bundle.min.js
  katex:
    css: https://cdn.jsdelivr.net/npm/katex@0.16.4/dist/katex.min.css